version: '3.8'

services:
    db:
        image: postgres:16
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports: # Expose ports to the host machine for local development
            - 2345:5432
        expose:
            - 5432
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready', '-U', '${POSTGRES_USER}']
            interval: 10s
            timeout: 5s
            retries: 5

    frontend:
        build: .
        ports:
            - 8501:8501
        depends_on:
            db:
                condition: service_healthy
        healthcheck:
            test: wget --no-verbose -O /dev/null --tries=1 http://localhost:8501 || exit 1
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    postgres_data:
